# For per pipeline config, check docs: https://www.elastic.co/guide/en/logstash/current/logstash-settings-file.html

- pipeline.id: app
  path.config: "/usr/share/logstash/pipeline/app.conf"
  queue.type: memory

#- pipeline.id: second_pipeline
#  path.config: "/usr/share/logstash/pipeline/second.conf"
#  queue.type: persisted
#  pipeline.batch.size: 125
#  queue.page_capacity: 50mb